- addon/components/info-banner-container.js
- addon/styles/_info-banner.scss
- addon/templates/components/info-banner.hbs
- app/components/info-banner-container.js
- app/templates/application.hbs
This just extends #12 so that it doesn't **delete** the functionality to add the survey banner. I'm just thinking that it would be useful to still have there next year 😉
> generalising the infoBanner

- package.json
This PR matches the upstream PR: https://github.com/empress/guidemaker/pull/15
@mansona highlighted that prember does not support node < 8 in the following post:
ember-learn/guides-app#402 (comment)
This project depends on the guidemaker project, which in turn has prember as a dependency, so it makes sense to remove node 6 from the engines tag and only support 8+
> remove unsupported node version

- index.js
- package-lock.json
- package.json
This bumps ember-auto-import to the latest version which was allowed by semver, and ensures it includes the Webpack polyfills that are necessary for Algolia search to work.
> [BUGFIX] Fixes autoimport, providing the proper Webpack polyfills

- tests/dummy/guides/release/index.md
Hello, I noticed that the link to the page was resulting in a 404, so I tried to make this adjustment.
> [Fix] Basic Markdown path link

- .travis.yml
- addon/helpers/contains.js
- addon/helpers/inc.js
- app/helpers/contains.js
- app/helpers/inc.js
- package-lock.json
- package.json
This PR (finally) gets CI running on PRs to the redesign branch and fixes build for recent ember versions because of the array helper override error 👍
> removing ember-composible-helpers to fix build

- addon/controllers/error.js
- addon/styles/_prism-overrides.scss
- app/controllers/error.js
- app/templates/error.hbs
- package-lock.json
- package.json
This PR makes it so that the removal diff isn't copy-pasted.
Before (all text can be highlighted for copy-paste):
After (red diff text is excluded from copy-paste):
See https://github.com/ember-learn/super-rentals-tutorial/issues/106 for motivation.
> don't include removal diff in copy-paste code, fix tests

- app/templates/components/guides-article.hbs
- package-lock.json
- package.json
Closes #76
@mansona is there a nicer way to pass this config variable? I would like to add this info to the CLI Guides.
cc @ijlee2 
How to test:
1. Run the app locally
2. In `app/templates/components/guides-article.hbs`, copy the "edit page" link markup and paste it into the template outside of the if statement. See that it has "main" in the path
3. Edit the dummy app config to remove the guidemaker-ember-template section
4. Restart the app, and look at the url. It should say `master` in it.
`master` is the default, so this is a non-breaking minor change.
> Add support for "main" branches in edit URLs

- app/templates/application.hbs
> Add ESProgress Bar component

- .github/workflows/ci.yml
- package.json
This is cherry-picking the changes to the CI file that were added to master in https://github.com/ember-learn/guidemaker-ember-template/pull/78
There are a few reasons for this change (not least making master and this branch match) but the reason I'm doing this now is because the following build failed for no good reason: https://github.com/ember-learn/guidemaker-ember-template/pull/80/checks?check_run_id=2850251718
as you can see it skipped the npm install because of the caching code, and as I discussed in the previous PR the caching is giving us very little so there is really no point in having it around 👍 if it's getting in our way at all then we should remove it
> updating to optimised Github CI file

- addon/styles/table-of-contents.css
Improved the Table of Content as discussed in #85. Made a version that looked similar to the current side bar.
https://user-images.githubusercontent.com/5811560/168754237-5355f620-0468-4b2b-b958-f43bf6410a8f.mov
**To discuss**
* I've not changed the width of the sidebar for now, I think that making it wider including the other content could benefit, but that would require overriding variables from style guide to make it look like the screenshot below. Imho it's not necessary yet.
> "New" design side menu

- addon/templates/components/info-banner.hbs
- addon/templates/components/search-input.hbs
- app/templates/components/chapter-links.hbs
- app/templates/components/guides-article.hbs
- app/templates/version/index.hbs
- app/templates/version/show.hbs
This fixes another one of our deprecations that happens around non AngleBracket `{{link-to}}` calls 👍
> run angle-brackets-codemod

- addon/styles/table-of-contents.css
Fixes #127  The styling of the border next to the menu is now the same as the `hr`
> Sidemenu styling

- addon/helpers/starts-with.js
I noticed some errors in the netlify build that seemed to be caused by the starts-with helper. This seemed like the easiest way to fix it 🤷
> Fix starts-with helper

- addon/styles/addon.css
With the change of the bottom margin of the header this margin was no longer necessary. 
**Before**
**After**
> Remove margin bottom from pencil

- addon/components/on-this-page.hbs
- addon/components/on-this-page.js
In the main ember guides we use showdown config to set a prefix for the header ids so that we didn't break links when we migrated to use Guidemaker for the guides
https://github.com/ember-learn/guides-source/blob/master/config/environment.js#L42-L45
This config needs to be read (if it exists) and set as a prefix to the links in the on-this-page component 👍
> add prefixHeaderId to on-this-page links

- addon/components/on-this-page.hbs
- addon/components/on-this-page.js
This reverts #154
Essentially it was a nice try to fix the problem but it didn't cover all use cases. The right thing to do was to use the showdown config defined in the environment to build the markdown that we use to find the links on the page with. 
This is the fix that we needed: https://github.com/empress/guidemaker/pull/92
> Revert "add prefixHeaderId to on-this-page links"

- app/templates/version.hbs
- this was breaking our guides-source redesign branch: https://github.com/ember-learn/guides-source/pull/1717
- related to: https://github.com/cibernox/ember-basic-dropdown/issues/614
> fix: add renderInPlace=true to EmberPowerSelect invocation in versions.hbs

- addon/styles/addon.css
- addon/styles/table-of-contents.css
Thanks a bunch for the recent styling revamp! It's great to see the guides being aligned with the overall branding.
I've noticed I find scanning through the new TOC harder as the font size is huge. This PR reuses the base font size for the TOC. It also sets a background color to make an easier difference between TOC and the article content, now that there's three side-by-side content panels. (with the new "on this page" panel)
I didn't talk this change through with anyone, so feel free to shoot it down if undesired. Or provide feedback so I can further tweak it 😄 
| Before | After |
| --- | --- |
| <img width="1436" alt="image" src="https://github.com/ember-learn/guidemaker-ember-template/assets/10243652/0bb898cc-02a1-45a6-876c-96e258389df0"> | <img width="1436" alt="image" …
> Sidebar styling tweaks

- package-lock.json
- package.json
- tests/dummy/guides/release/examples/syntax-highlighting.md
A whole series of small PRs has the cumulative goal of making json5 support and any other kinds of source examples we need available to the guides.
*  `ember-showdown-prism` 4.4.0 has typescript and json5 support in its `ember-prism` settings.
*  empress/guidemaker PR#93, now in review, removes its override of the settings, so that the settings specified in `ember-showdown-prism` will take effect. 
* This PR causes the ember template to use the new version of ember-showdown-prism. 
To date, this change isn't using the new guidemaker, so it will need to be updated once more as soon as that change is released. It also needs typescript and json5 code samples in its test app, so that running the test app will test all three together. Then it can undergo final review.
Once all that is done, …
> Bumped e-showdown-prism dep to 4.4

- addon/helpers/html-safe.js
- package-lock.json
- package.json
- tests/dummy/mirage/fixtures/search-response.js
Fixes #165
This PR adds the `<Input>` example to the mirage fixture. It uses the [default settings](https://github.com/apostrophecms/sanitize-html#default-options) from the package.
With the `disallowedTagsMode: 'escape'` we make sure the tag still shows up in the result.
With `lowerCaseTags: false`, passed to the [parser](https://github.com/apostrophecms/sanitize-html#htmlparser2-options) we make sure that the Ember components retain their caps.
> Use Sanitize-HTML to not render input fields in our search response

- package-lock.json
- package.json
- tests/dummy/config/environment.js
This switches to the latest stable release of [`ember-showdown-shiki`](https://github.com/IgnaceMaes/ember-showdown-shiki):
- Rename from `shikiji` to `shiki`
- And contains some bug fixes
> deps: upgrade to ember-showdown-shiki

- addon/components/on-this-page.hbs
- addon/styles/on-this-page.css
- tests/integration/components/on-this-page-test.js
Implements https://github.com/ember-learn/guidemaker-ember-template/issues/179
- Only shows h1, h2, and h3 in the "on this page" section
- Indents h3 levels with left padding
- h2 not indented as I believe it should be the base and h1 should be kept for the title only (see related fix: https://github.com/ember-learn/guides-source/pull/2012)
| Before | After |
| --- | --- |
|  <img width="239" src="https://github.com/ember-learn/guidemaker-ember-template/assets/10243652/72f39e03-00f6-440b-b993-131acdad45d3"> | <img width="248" src="https://github.com/ember-learn/guidemaker-ember-template/assets/10243652/3ceaa8b0-e4b2-49b3-b4ca-3147f60de844"> |
To be fair, this example doesn't properly showcase the real difference, and a real content page would be better suited to test.
EDIT: test using the …
> style: update "on this page" to only show headers up until level 3 and indent

- addon/styles/on-this-page.css
- tests/acceptance/chapter-links-test.js
- tests/dummy/guides/release/guide-test/index.md
- tests/dummy/guides/release/pages.yml
Implements part of https://github.com/ember-learn/guidemaker-ember-template/issues/182
Makes the "On This Page" section sticky
Test: https://deploy-preview-184--guidemaker-ember-template.netlify.app/release/guide-test
> style: make on-this-page sticky

- guidemaker-ember-template/.prettierrc.cjs
- guidemaker-ember-template/src/components/guides-article.hbs
- guidemaker-ember-template/src/components/guides-article.js
- guidemaker-ember-template/src/templates/version/index.gjs
- guidemaker-ember-template/src/templates/version/show.gjs
- test-app/tests/integration/components/guides-article-test.js
For better readability, I have only formatted the the code in the first commit. I would recommend to ignore whitespaces.
> Transform guides-article to glimmer component

- guidemaker-ember-template/src/components/chapter-links.hbs
- guidemaker-ember-template/src/components/chapter-links.js
- guidemaker-ember-template/src/components/guides-article.hbs
- test-app/tests/acceptance/chapter-links-test.js
- test-app/tests/integration/components/chapter-links-test.js
For better readability, I have only formatted the the code in the first commit. I would recommend to ignore whitespaces.
> Transform chapter-links to glimmer component

- .github/workflows/ci.yml
- test-app/config/ember-try.js
- add lts-5.12 because it's the newest supported ember
- move ember-release to allowed failures because 6.0 is not yet supported
> adjust test matrix to reflect current supported ember versions

- guidemaker-ember-template/src/components/guides-article.hbs
- guidemaker-ember-template/src/components/guides-article.js
- guidemaker-ember-template/src/styles/addon.css
- test-app/config/environment.js
This pull request introduces a new informational banner to the guides article page when the current version is GJS, and updates related styles for consistency and improved accessibility. The most significant changes are the addition of the GJS info banner component, updates to CSS for the new banner, and several minor style consistency improvements.
**Feature addition:**
* Added a conditional info banner to `guides-article.hbs` that appears when the current version is GJS, informing users that the guide assumes GJS usage and linking to more information. The banner includes an accessible SVG icon and appropriate ARIA labels.
**Styling and consistency improvements:**
* Updated `.info-banner-wrapper` and related CSS classes in `addon.css` to style the new info banner, including layout, …
> [FEATURE GJS Banner] add GJS Format banner for currentVersion
